;;; bnpa:blee-libs.el --- Blee Native Pkg Adoption (blee-libs)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]Summary:  bnpa Adoption of :blee-libs
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
* Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  ~ORG-TOP-CONTROLS-COME-HERE~
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;(require 'blee-libs)
(require 'straight)
(require 'blee-lib-general)

(setq blee:dev:mode? t)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bnpa:blee-libs:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bnpa:blee-libs:usgEnabled? t "blee-libs package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:blee-libs/fullUpdate>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:blee-libs/fullUpdate ()
 "blee-libs package adoption control."
 (interactive)
  (blee:ann|this-func (compile-time-function-name))
  (when bnpa:blee-libs:usgEnabled?
    (bnpa:blee-libs:install/update)
    (bnpa:blee-libs:config/main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:blee-libs:install/update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:blee-libs:install/update ()
 "blee-libs package adoption install/update template."
 (interactive)
  (blee:ann|this-func (compile-time-function-name))
  (unless blee:dev:mode?
    (straight-use-package
     '(blee-libs :type git :host github :repo "bx-blee/blee-libs")))

  (when blee:dev:mode?
    (straight-use-package
     '(blee-libs :local-repo "/bisos/git/bxRepos/blee/blee-libs")))
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:blee-libs:install/update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:blee-libs:config/main ()
 "blee-libs package adoption config template."
 (interactive)
  (blee:ann|this-func (compile-time-function-name))
;;;#+END:
  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bnpa:blee-libs)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
