;;; bcpg:ghostelPlus.el --- Blee Component Pkg Grouping (ghostelPlus)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bcpg" :pkgName "ghostelPlus"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bcpg Adoption of :ghostelPlus
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText
Initiated with yasnippet at: bx-comeega-elisp-mode/begin/packageAdoption [[elisp:(org-shifttab)][<)]] E|
Yes" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Summary:
" orgCmntEnd)

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* *[[elisp:(org-cycle)][| Proclamations |]]* :: Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
** Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  [[elisp:(org-cycle)][|/Controls/| ]] :: [[elisp:(org-show-subtree)][|=]]  [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[file:Panel.org][Panel]] | [[elisp:(blee:ppmm:org-mode-toggle)][Nat]] | [[elisp:(bx:org:run-me)][Run]] | [[elisp:(bx:org:run-me-eml)][RunEml]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]]  [[elisp:(save-buffer)][Save]]  [[elisp:(kill-buffer)][Quit]] [[elisp:(org-cycle)][| ]]
** /Version Control/ ::  [[elisp:(call-interactively (quote cvs-update))][cvs-update]]  [[elisp:(vc-update)][vc-update]] | [[elisp:(bx:org:agenda:this-file-otherWin)][Agenda-List]]  [[elisp:(bx:org:todo:this-file-otherWin)][ToDo-List]]
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:


(require 'blee-libs)
(require 'straight)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bcpg" :pkgName "ghostelPlus"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bcpg:ghostelPlus:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bcpg:ghostelPlus:usgEnabled? t "ghostelPlus package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "ghostelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:ghostelPlus|fullUpdate>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:ghostelPlus|fullUpdate ()
   " #+begin_org
** DocStr: *ghostelPlus* package adoption full update template.
#+end_org "
 (b:log|entry (b:func$entry)) (when bcpg:ghostelPlus:usgEnabled?
    (bcpg:ghostelPlus:install|update)
    (bcpg:ghostelPlus:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "ghostelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:ghostelPlus:install|update>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:ghostelPlus:install|update ()
   " #+begin_org
** DocStr: ghostelPlus Component Package Adoption install or update template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:

   (orgCmntBegin "
** [[elisp:(show-all)][(>]]  =component= ~ghostel~ *pkgDesc* [[elisp:(org-shifttab)][<)]] E|
*** TODO NOT b:pkg:forked|is?
" orgCmntEnd)

     (cond ((b:pkg:forked|is?  'ghostel)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(ghostel :local-repo b:pkg:forked|basedir)))
           ((b:pkg:devel|is?  'ghostel)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(ghostel :local-repo b:pkg:devel|basedir)))
           (t
            (b:pkg:straight|profiledInstall
            b:pkgsProfile:adopted
            '(ghostel :type git :host github :repo "dakra/ghostel")))
            )

     )


;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "ghostelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:ghostelPlus:config|main>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:ghostelPlus:config|main ()
   " #+begin_org
** DocStr: *ghostelPlus* package adoption config template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:
  "Configure ghostel settings, hooks, and integrations."

  (require 'ghostel)

  ;; ghostel is a terminal emulator powered by libghostty.  Defaults shown.
  ;; The native module is installed on first interactive use (see
  ;; `ghostel-module-auto-install' below).

  ;; --- Shell & Environment ---
  ;; (setq ghostel-shell (or (getenv "SHELL") "/bin/sh"))       ; string, or (PATH ARGS...)
  ;; (setq ghostel-environment nil)                             ; extra "KEY=VALUE" entries (bare "KEY" unsets)
  ;; (setq ghostel-macos-login-shell (eq system-type 'darwin))  ; wrap via login(1) on macOS

  ;; --- Terminal Type ---
  ;; (setq ghostel-term "xterm-ghostty")                        ; advertises ghostty caps (synced output, etc.)
  ;;   ; set to "xterm-256color" to fall back to a generic terminal

  ;; --- Scrollback ---
  ;; (setq ghostel-max-scrollback (* 5 1024 1024))              ; bytes (~5,000 rows at 80 cols); materialized for isearch

  ;; --- Buffer Naming & Lifecycle ---
  ;; (setq ghostel-buffer-name "*ghostel*")                     ; default buffer name
  ;; (setq ghostel-buffer-name-function #'ghostel-buffer-name-by-title)
  ;;   ; or #'ghostel-buffer-name-by-directory, or nil to disable renaming
  ;; (setq ghostel-project-buffer-scope 'both)                  ; default-directory | identity | both
  ;; (setq ghostel-kill-buffer-on-exit t)                       ; kill buffer when shell exits
  ;; (setq ghostel-query-before-killing 'auto)                  ; t | nil | auto (query only while a command runs)

  ;; --- Redraw & Performance ---
  ;; (setq ghostel-adaptive-fps t)                              ; shorter initial delay, idle when quiet
  ;; (setq ghostel-timer-delay 0.033)                           ; base redraw delay (~30fps)
  ;; (setq ghostel-input-coalesce-delay 0.003)                  ; batch rapid keystrokes (0 to disable)
  ;; (setq ghostel-full-redraw nil)                             ; t is more robust for aggressive TUIs, costs CPU
  ;; (setq ghostel-cell-pixel-scale 'auto)                      ; HiDPI cell-size reporting for image protocols
  ;; (setq ghostel-scroll-on-input t)                           ; snap to bottom on input

  ;; --- Detection & Notifications ---
  ;; (setq ghostel-enable-url-detection t)                      ; linkify plain http(s):// URLs
  ;; (setq ghostel-enable-file-detection t)                     ; linkify /path/file:line refs
  ;; (setq ghostel-detect-password-prompts t)                   ; pop `read-passwd' on detected prompts
  ;; (setq ghostel-notification-function #'ghostel-default-notify) ; OSC 9/777 desktop notifications (nil to ignore)

  ;; --- Shell Integration (OSC 133 semantic prompts) ---
  ;; (setq ghostel-shell-integration t)                         ; auto-inject for bash/zsh/fish
  ;; (setq ghostel-tramp-shell-integration nil)                 ; enable over TRAMP connections

  ;; --- Native Module ---
  ;; (setq ghostel-module-auto-install 'ask)                    ; ask | download | compile | nil
  ;; (setq ghostel-module-directory nil)                        ; nil = package dir; set outside pkg tree to survive rebuilds

  ;; --- Clipboard ---
  ;; (setq ghostel-enable-osc52 nil)                            ; allow apps to set clipboard via OSC 52 (off for security)

  ;; --- Hooks ---
  ;; (add-hook 'ghostel-exit-functions #'my-fn)                 ; (buffer event-string) on process exit
  ;; (add-hook 'ghostel-command-start-functions #'my-fn)        ; (buffer) on OSC 133 C (command start)
  ;; (add-hook 'ghostel-command-finish-functions #'my-fn)       ; (buffer exit-status) on OSC 133 D (command finish)
  ;; (add-hook 'ghostel-pre-spawn-hook #'my-fn)                 ; no args; `process-environment' bound to the child env

  ;; --- Commands (no default global prefix; bind to taste) ---
  ;;   ; M-x ghostel                     start a terminal
  ;;   ; M-x ghostel-project             start a project-scoped terminal
  ;;   ; M-x ghostel-next / -previous    cycle ghostel buffers
  ;;   ; M-x ghostel-list-buffers        list ghostel buffers
  ;;   ; M-x ghostel-project-next / -previous / -list-buffers
  ;;   ; M-x ghostel-compile             run a compilation in a ghostel terminal

  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bcpg:ghostelPlus)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
