;;; bcpg:gptelPlus.el --- Blee Component Pkg Grouping (gptelPlus)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bcpg" :pkgName "gptelPlus"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bcpg Adoption of :gptelPlus
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText
Initiated with yasnippet at: bx-comeega-elisp-mode/begin/packageAdoption [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Summary:
" orgCmntEnd)

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* *[[elisp:(org-cycle)][| Proclamations |]]* :: Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
** Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  [[elisp:(org-cycle)][|/Controls/| ]] :: [[elisp:(org-show-subtree)][|=]]  [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[file:Panel.org][Panel]] | [[elisp:(blee:ppmm:org-mode-toggle)][Nat]] | [[elisp:(bx:org:run-me)][Run]] | [[elisp:(bx:org:run-me-eml)][RunEml]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]]  [[elisp:(save-buffer)][Save]]  [[elisp:(kill-buffer)][Quit]] [[elisp:(org-cycle)][| ]]
** /Version Control/ ::  [[elisp:(call-interactively (quote cvs-update))][cvs-update]]  [[elisp:(vc-update)][vc-update]] | [[elisp:(bx:org:agenda:this-file-otherWin)][Agenda-List]]  [[elisp:(bx:org:todo:this-file-otherWin)][ToDo-List]]
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:


(require 'blee-libs)
(require 'straight)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bcpg" :pkgName "gptelPlus"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bcpg:gptelPlus:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bcpg:gptelPlus:usgEnabled? t "gptelPlus package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "gptelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:gptelPlus|fullUpdate>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:gptelPlus|fullUpdate ()
   " #+begin_org
** DocStr: *gptelPlus* package adoption full update template.
#+end_org "
 (b:log|entry (b:func$entry)) (when bcpg:gptelPlus:usgEnabled?
    (bcpg:gptelPlus:install|update)
    (bcpg:gptelPlus:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "gptelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:gptelPlus:install|update>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:gptelPlus:install|update ()
   " #+begin_org
** DocStr: gptelPlus Component Package Adoption install or update template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:

   (orgCmntBegin "
** [[elisp:(show-all)][(>]]  =component= ~gptel~~ *pkgDesc* [[elisp:(org-shifttab)][<)]] E|
*** TODO NOT b:pkg:forked|is?
" orgCmntEnd)
     (cond ((b:pkg:forked|is?  'gptel)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(gptel :local-repo b:pkg:forked|basedir)))
           ((b:pkg:devel|is?  'gptel)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(gptel :local-repo b:pkg:devel|basedir)))
           (t
            (b:pkg:straight|profiledInstall
            b:pkgsProfile:adopted
            '(gptel :type git :host github :repo "karthink/gptel")))
            )

     (b:pkg:straight|profiledInstall
      b:pkgsProfile:adopted
      '(gptel-quick :type git :host github :repo "karthink/gptel-quick"))
     )


;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "gptelPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:gptelPlus:config|main>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:gptelPlus:config|main ()
   " #+begin_org
** DocStr: *gptelPlus* package adoption config template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:
  "Configure gptel for use with OpenAI and gpt-4o."
  (require 'gptel)

  ;; ;; Use the API key from env or set it here directly (not recommended for public configs)
  ;; (unless (getenv "OPENAI_API_KEY")
  ;;   (setenv "OPENAI_API_KEY" "sk-...your-key..."))  ;; Optional fallback

  ;; ;; Set default model and backend
  ;; (setq gptel-backend
  ;;       (gptel-make-openai
  ;;        "openai"
  ;;        :protocol "https"
  ;;        :host "api.openai.com/v1"
  ;;        :models '("gpt-4o" "gpt-4-turbo" "gpt-3.5-turbo")
  ;;        :stream t))  ;; Enable streaming outpu


  (setq gptel-api-key (lambda () (shell-command-to-string "echo -n $(cat  /bxo/usg/bystar/bpos/usageEnvs/fullUse/credentials/openAi/openAiApiKey)")))

  (global-set-key (kbd "C-c RET") 'gptel-send)
  (setq gptel-model 'gpt-4o)  ;; Default model

  ;; Optional: better buffer naming
  (setq gptel--buffer-prefix "*gptel: ")

  ;; Optional: save conversation history
  (setq gptel-save-chat-prompt t)

  ;; (keymap-set embark-general-map "?" #'gptel-quick)
)

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bcpg:gptelPlus)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
