;;; bcpg:aidermacsPlus.el --- Blee Component Pkg Grouping (aidermacsPlus)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bcpg" :pkgName "aidermacsPlus"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bcpg Adoption of :aidermacsPlus
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText
Initiated with yasnippet at: bx-comeega-elisp-mode/begin/packageAdoption [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Summary:
" orgCmntEnd)

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* *[[elisp:(org-cycle)][| Proclamations |]]* :: Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
** Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  [[elisp:(org-cycle)][|/Controls/| ]] :: [[elisp:(org-show-subtree)][|=]]  [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[file:Panel.org][Panel]] | [[elisp:(blee:ppmm:org-mode-toggle)][Nat]] | [[elisp:(bx:org:run-me)][Run]] | [[elisp:(bx:org:run-me-eml)][RunEml]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]]  [[elisp:(save-buffer)][Save]]  [[elisp:(kill-buffer)][Quit]] [[elisp:(org-cycle)][| ]]
** /Version Control/ ::  [[elisp:(call-interactively (quote cvs-update))][cvs-update]]  [[elisp:(vc-update)][vc-update]] | [[elisp:(bx:org:agenda:this-file-otherWin)][Agenda-List]]  [[elisp:(bx:org:todo:this-file-otherWin)][ToDo-List]]
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:


(require 'blee-libs)
(require 'straight)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bcpg" :pkgName "aidermacsPlus"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bcpg:aidermacsPlus:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bcpg:aidermacsPlus:usgEnabled? t "aidermacsPlus package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "aidermacsPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:aidermacsPlus|fullUpdate>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:aidermacsPlus|fullUpdate ()
   " #+begin_org
** DocStr: *aidermacsPlus* package adoption full update template.
#+end_org "
 (b:log|entry (b:func$entry)) (when bcpg:aidermacsPlus:usgEnabled?
    (bcpg:aidermacsPlus:install|update)
    (bcpg:aidermacsPlus:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "aidermacsPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:aidermacsPlus:install|update>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:aidermacsPlus:install|update ()
   " #+begin_org
** DocStr: aidermacsPlus Component Package Adoption install or update template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:

   (orgCmntBegin "
** [[elisp:(show-all)][(>]]  =component= ~aidermacs~~ *pkgDesc* [[elisp:(org-shifttab)][<)]] E|
*** TODO NOT b:pkg:forked|is?
" orgCmntEnd)
     (cond ((b:pkg:forked|is?  'aidermacs)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(aidermacs :local-repo b:pkg:forked|basedir)))
           ((b:pkg:devel|is?  'aidermacs)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(aidermacs :local-repo b:pkg:devel|basedir)))
           (t
            (b:pkg:straight|profiledInstall
            b:pkgsProfile:adopted
            '(aidermacs :type git :host github :repo "MatthewZMD/aidermacs")))
            ))

;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "aidermacsPlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:aidermacsPlus:config|main>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:aidermacsPlus:config|main ()
   " #+begin_org
** DocStr: *aidermacsPlus* package adoption config template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:
  "Minimal setup for aidermacs without project.el, with magit support and safe chat mode."
  (require 'aidermacs)

  
  ;; Use Git root detection only (no project.el)
  (setq aider-project-root-function
        (lambda ()
          (or (locate-dominating-file default-directory ".git")
              default-directory)))

  ;; Enable chat mode automatically for files in current aider session
  (defun my/aider-enable-chat-mode-if-in-session ()
    "Enable `aider-chat-mode` only if this file is part of the current aider session."
    (when (and (fboundp 'aider-chat--file-in-chat-session-p)
               buffer-file-name
               (aider-chat--file-in-chat-session-p buffer-file-name))
      (aider-chat-mode 1)))

  (add-hook 'find-file-hook #'my/aider-enable-chat-mode-if-in-session)

  ;; Optional: set preferred model
  (setq aidermacs-default-model "gpt-4o")
  ;; (setq aider-default-model "gpt-4-turbo")

  ;; (setq aider-command "/bisos/pipx/bin/aidermacs")

  ;; Optional: link with magit (by default, aider uses git diffs)
  ;; No explicit integration needed here unless you want to customize commit handling.
  ;; But we can add a helper if you want tighter control.
)


;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bcpg:aidermacsPlus)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
