;;; bcpg:claudePlus.el --- Blee Component Pkg Grouping (claude-codePlus)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bcpg" :pkgName "claude-codePlus"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bcpg Adoption of :claude-codePlus
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText
Initiated with yasnippet at: bx-comeega-elisp-mode/begin/packageAdoption [[elisp:(org-shifttab)][<)]] E|
Yes" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Summary:
" orgCmntEnd)

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* *[[elisp:(org-cycle)][| Proclamations |]]* :: Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
** Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  [[elisp:(org-cycle)][|/Controls/| ]] :: [[elisp:(org-show-subtree)][|=]]  [[elisp:(show-all)][Show-All]]  [[elisp:(org-shifttab)][Overview]]  [[elisp:(progn (org-shifttab) (org-content))][Content]] | [[file:Panel.org][Panel]] | [[elisp:(blee:ppmm:org-mode-toggle)][Nat]] | [[elisp:(bx:org:run-me)][Run]] | [[elisp:(bx:org:run-me-eml)][RunEml]] | [[elisp:(delete-other-windows)][(1)]] | [[elisp:(progn (save-buffer) (kill-buffer))][S&Q]]  [[elisp:(save-buffer)][Save]]  [[elisp:(kill-buffer)][Quit]] [[elisp:(org-cycle)][| ]]
** /Version Control/ ::  [[elisp:(call-interactively (quote cvs-update))][cvs-update]]  [[elisp:(vc-update)][vc-update]] | [[elisp:(bx:org:agenda:this-file-otherWin)][Agenda-List]]  [[elisp:(bx:org:todo:this-file-otherWin)][ToDo-List]]
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:


(require 'blee-libs)
(require 'straight)
(require 'bcpg:vtermPlus)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bcpg" :pkgName "claude-codePlus"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bcpg:claude-codePlus:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bcpg:claude-codePlus:usgEnabled? t "claude-codePlus package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "claude-codePlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:claude-codePlus|fullUpdate>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:claudePlus|fullUpdate ()
   " #+begin_org
** DocStr: *claude-codePlus* package adoption full update template.
#+end_org "
 (b:log|entry (b:func$entry)) (when bcpg:claude-codePlus:usgEnabled?
    (bcpg:claude-codePlus:install|update)
    (bcpg:claude-codePlus:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "claude-codePlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:claude-codePlus:install|update>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:claude-codePlus:install|update ()
   " #+begin_org
** DocStr: claude-codePlus Component Package Adoption install or update template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:

   (orgCmntBegin "
** [[elisp:(show-all)][(>]]  =component= ~claude-code~~ *pkgDesc* [[elisp:(org-shifttab)][<)]] E|
*** TODO NOT b:pkg:forked|is?
" orgCmntEnd)

     (cond ((b:pkg:forked|is?  'claude-code)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(claude-code :local-repo b:pkg:forked|basedir)))
           ((b:pkg:devel|is?  'claude-code)
            (b:pkg:straight|profiledInstall
             b:pkgsProfile:blee3:adopted
             '(claude-code :local-repo b:pkg:devel|basedir)))
           (t
            (b:pkg:straight|profiledInstall
            b:pkgsProfile:adopted
            '(claude-code :type git :host github :repo "stevemolitor/claude-code.el" :branch "main" :depth 1
                   :files ("*.el" (:exclude "images/*")))))
            )

     )


;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "claude-codePlus"
(orgCmntBegin "
*  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_ _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_ [[elisp:(outline-show-branches+toggle)][|=]] [[elisp:(bx:orgm:indirectBufOther)][|>]] *[[elisp:(blee:ppmm:org-mode-toggle)][|N]]*  defun      [[elisp:(outline-show-subtree+toggle)][||]]  <<bcpg:claude-codePlus:config|main>>  --  --   [[elisp:(org-cycle)][| ]]
" orgCmntEnd)
(defun bcpg:claude-codePlus:config|main ()
   " #+begin_org
** DocStr: *claude-codePlus* package adoption config template.
#+end_org "
 (b:log|entry (b:func$entry))
;;;#+END:
  "Configure claude-code package settings, hooks, and integrations."

  (add-hook 'claude-code-process-environment-functions #'monet-start-server-function)

  ;; --- Terminal & Display ---
  ;; (setq claude-code-program "claude")                        ; path to Claude executable
  ;; (setq claude-code-program-switches nil)                    ; extra CLI args list
  ;; (setq claude-code-sandbox-program nil)                     ; path to sandbox binary
  ;; (setq claude-code-terminal-backend 'eat)                   ; 'eat (default), 'vterm, or 'ghostel
  ;; (setq claude-code-term-name "xterm-256color")              ; terminal type
  ;; (setq claude-code-startup-delay 0.1)                       ; init delay in seconds

  ;; --- Buffer & Interaction ---
  ;; (setq claude-code-large-buffer-threshold 100000)           ; chars before confirm on send
  ;; (setq claude-code-newline-keybinding-style 'newline-on-shift-return)
  ;;   ; options: newline-on-shift-return, newline-on-alt-return,
  ;;   ;          shift-return-to-send, super-return-to-send
  ;; (setq claude-code-enable-notifications t)                  ; notify when Claude awaits input
  ;; (setq claude-code-notification-function 'claude-code-default-notification)
  ;; (setq claude-code-confirm-kill t)                          ; prompt before killing instances
  ;; (setq claude-code-toggle-auto-select nil)                  ; auto-focus buffer on toggle open

  ;; --- Window Management ---
  ;; (setq claude-code-no-delete-other-windows nil)             ; prevent window from being closed
  ;; (setq claude-code-optimize-window-resize t)                ; optimize terminal reflow (width only)
  ;; (setq claude-code-display-window-fn 'claude-code-display-buffer-below)

  ;; --- Image Paste ---
  ;; (setq claude-code-enable-image-paste t)                    ; enable clipboard image pasting
  ;; (setq claude-code-image-paste-cleanup-on-kill t)           ; delete tmp images on buffer kill
  ;; (setq claude-code-image-paste-directory "/tmp")            ; dir for temporary image files

  ;; --- Eat Backend ---
  ;; (setq claude-code-eat-read-only-mode-cursor-type '(box nil nil))

  ;; --- Vterm Backend ---
  ;; (setq claude-code-vterm-buffer-multiline-output t)         ; batch output to prevent flicker
  ;; (setq claude-code-vterm-multiline-delay 0.01)              ; delay before processing output

  ;; --- Hooks ---
  ;; (add-hook 'claude-code-start-hook #'my-fn)                 ; runs after Claude starts
  ;; (add-hook 'claude-code-process-environment-functions #'my-fn) ; customize process env (args: buffer-name dir)
  ;; (add-hook 'claude-code-event-hook #'my-fn)                 ; fires on CLI events (plist: :type :buffer-name)

  ;; --- Key Bindings (prefix C-c c via claude-code-command-map) ---
  ;; (global-set-key (kbd "C-c c") claude-code-command-map)
  ;;   ; C-c c m  claude-code-transient                (menu)
  ;;   ; C-c c c  claude-code                          (start)
  ;;   ; C-c c d  claude-code-start-in-directory
  ;;   ; C-c c C  claude-code-continue
  ;;   ; C-c c R  claude-code-resume
  ;;   ; C-c c i  claude-code-new-instance
  ;;   ; C-c c k  claude-code-kill
  ;;   ; C-c c K  claude-code-kill-all
  ;;   ; C-c c s  claude-code-send-command
  ;;   ; C-c c x  claude-code-send-command-with-context
  ;;   ; C-c c r  claude-code-send-region
  ;;   ; C-c c o  claude-code-send-buffer-file
  ;;   ; C-c c e  claude-code-fix-error-at-point
  ;;   ; C-c c f  claude-code-fork
  ;;   ; C-c c /  claude-code-slash-commands
  ;;   ; C-c c t  claude-code-toggle
  ;;   ; C-c c b  claude-code-switch-to-buffer
  ;;   ; C-c c B  claude-code-select-buffer
  ;;   ; C-c c z  claude-code-toggle-read-only-mode
  ;;   ; C-c c M  claude-code-cycle-mode
  ;;   ; C-c c p  claude-code-yank-media               (paste image)
  ;;   ; C-c c S  claude-code-start-sandbox

  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bcpg:claudePlus)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
