;;; bcpg:toolbar.el --- Blee Component Pkg Grouping (toolbar)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bcpg" :pkgName "toolbar"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bcpg Adoption of :toolbar
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText
Initiated with yasnippet at: bx-comeega-elisp-mode/begin/packageAdoption [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Summary:
" orgCmntEnd)

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
* Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  ~ORG-TOP-CONTROLS-COME-HERE~
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:


(require 'blee-libs)
(require 'straight)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bcpg" :pkgName "toolbar"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bcpg:toolbar:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bcpg:toolbar:usgEnabled? t "toolbar package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "toolbar"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bcpg:toolbar|fullUpdate>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bcpg:toolbar|fullUpdate ()
 "toolbar package adoption control."
 (b:log|entry (b:func$entry))
  (when bcpg:toolbar:usgEnabled?
    (bcpg:toolbar:install|update)
    (bcpg:toolbar:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "toolbar"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bcpg:toolbar:install|update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bcpg:toolbar:install|update ()
 "toolbar package adoption install or update template."
 (b:log|entry (b:func$entry))
;;;#+END:
   ;;; Installation Material Comes Here
   )

;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "ready" :pkgAdoptionType "bcpg" :pkgName "toolbar"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bcpg:toolbar:install|update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bcpg:toolbar:config|main ()
 "toolbar package adoption config template."
 (b:log|entry (b:func$entry))
;;;#+END:

   (tooltip-mode 1)

 (add-to-list 'image-load-path (expand-file-name "/bisos/blee/env3/images"))

  (when (find-image '((:type xpm :file "bxLogo-30.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    (tool-bar-add-item 
     "bxLogo-30" ;; "next-page" "letter"
     'bx:Bxa
     'BxA
     :help "Go To Top Level ByStar Panel"))

  (when (find-image '((:type xpm :file "letter.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    (tool-bar-add-item "letter" 'toggle-input-method 'ف/E
    :help "Toggle Input Method (Language)"
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    ;;(setq tool-bar-map (make-sparse-keymap))
    (tool-bar-add-item "letter" 'delete-other-windows 'W1
    :help "Delete Other Windows"
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    ;;(setq tool-bar-map (make-sparse-keymap))
    (tool-bar-add-item "letter" 'split-window-below 'W2
    :help "Split Window Below"
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    ;;(setq tool-bar-map (make-sparse-keymap))
    (tool-bar-add-item "letter" 'split-window-right 'W3
    :help "Split Window Right"    
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    (tool-bar-add-item "letter" 'blee:ppmm:org-mode-toggle 'TM
    :help "Bx: Toggle Major Mode Between Native and Org-Mode"    
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (tool-bar-mode 1))
    (tool-bar-add-item "letter" 'blee:ppmm:org-mode-content-list 'CL
    :help "Bx: Switch To Org-Mode, view at top level and goto contents list"    
    ))

  (when (find-image '((:type xpm :file "next-page.xpm")))
    (unless tool-bar-mode (goto-char (point-min)))
    (tool-bar-add-item "letter" 'blee:ppmm:org-mode-content-list 'Top
    :help "Bx: beginning-of-buffer"    
    ))
  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bcpg:toolbar)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
