;;; bnpa:comeega.el --- Blee Native Pkg Adoption (comeega)  -*- lexical-binding: t; -*-

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "comeega"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bnpa Adoption of :comeega
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
* Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  ~ORG-TOP-CONTROLS-COME-HERE~
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

(require 'straight)
(require 'blee-libs)
;;(require 'blee-lib-general)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "bnpa" :pkgName "comeega"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<bnpa:comeega:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar bnpa:comeega:usgEnabled? t "comeega package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "comeega"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:comeega|fullUpdate>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:comeega|fullUpdate ()
 "comeega package adoption control."
 (interactive) (b:log|entry (b:func$entry))
  (when bnpa:comeega:usgEnabled?
    (bnpa:comeega:install|update)
    (bnpa:comeega:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "comeega"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:comeega:install|update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:comeega:install|update ()
 "comeega package adoption install/update template."
 (interactive)
 (b:log|entry (b:func$entry))
 (if b:g:dev:mode?
      (straight-use-package
       '(comeega :local-repo "/bisos/git/bxRepos/blee/comeega"))
    (straight-use-package
     '(comeega :type git :host github :repo "bx-blee/comeega"))))
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "comeega"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<bnpa:comeega:install|update>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun bnpa:comeega:config|main ()
 "comeega package adoption config template."
 (interactive)
 (b:log|entry (b:func$entry))

;;;#+END:
  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bnpa:comeega)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
