;;; bnpa:blee-libs.el --- Blee Native Pkg Adoption (blee-libs)  -*- lexical-binding: t; -*-

(message (format "Loaded: %s" load-file-name))

;;;#+BEGIN: b:elisp:pkg/summaryText :outLevel 1 :pkgAdoptionType "bnpa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]] Summary:  bnpa Adoption of :blee-libs
Machine Generated By org-dblock-write:b:elisp:pkg/summaryText [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/copyLeftPlus :outLevel 1
(orgCmntBegin "
* Libre-Halaal Software --- Part Of Blee ---  Poly-COMEEGA Format.
** This is Libre-Halaal Software. © Libre-Halaal Foundation. Subject to AGPL.
** It is not part of Emacs. It is part of Blee.
** Best read and edited  with Poly-COMEEGA (Polymode Colaborative Org-Mode Enhance Emacs Generalized Authorship)
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/authors :authors ("./inserts/authors-mb.org")
(orgCmntBegin "
* Authors: Mohsen BANAN, http://mohsen.banan.1.byname.net/contact
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:file/orgTopControls :outLevel 1
(orgCmntBegin "
*  ~ORG-TOP-CONTROLS-COME-HERE~
" orgCmntEnd)
;;;#+END:

(orgCmntBegin "
* Commentary, Model and Terminology:
* Relevant Panels:
** [[file:/bisos/panels/blee-core/mail/model/_nodeBase_/fullUsagePanel-en.org]]
** [[file:/bisos/panels/blee-core/mail/Gnus/_nodeBase_/fullUsagePanel-en.org]]
* Planned Improvements:
" orgCmntEnd)

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "REQUIRES" :extraInfo "Imports"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _REQUIRES_: |]]  Imports  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

(require 'straight)


;(setq blee:dev:mode? t)  ;;; On a per module bases overwrite dev:mode?

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 1 :title "Variables And Constants" :extraInfo "defvar, defcustom"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_       [[elisp:(outline-show-subtree+toggle)][| *Variables And Constants:* |]]  defvar, defcustom  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/usgEnabled?defvar :outLevel 2 :pkgAdoptionType "b:npa" :pkgName "blee-libs"
(orgCmntBegin "
** [[elisp:(show-all)][(>]]  =defvar= <<b:npa:blee-libs:usgEnabled?>> [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defvar b:npa:blee-libs:usgEnabled? t "blee-libs package adoption control.")
;;;#+END:

;;;#+BEGIN: blee:bxPanel:foldingSection :outLevel 0 :title "Common Facilities" :extraInfo "Library Candidates"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  _[[elisp:(blee:menu-sel:outline:popupMenu)][±]]_  _[[elisp:(blee:menu-sel:navigation:popupMenu)][Ξ]]_     [[elisp:(outline-show-subtree+toggle)][| _Common Facilities_: |]]  Library Candidates  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;;#+END:

;;;#+BEGIN: b:elisp:pkg/fullUpdate :outLevel 1 :pkgsStage "noLibs" :pkgAdoptionType "b:npa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<b:npa:blee-libs|fullUpdate>>  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun b:npa:blee-libs|fullUpdate ()
   " #+begin_org
** DocStr: *blee-libs* package adoption full update template.
#+end_org "
 (when b:npa:blee-libs:usgEnabled?
    (b:npa:blee-libs:install|update)
    (b:npa:blee-libs:config|main)
    )
  )
;;;#+END:

;;;#+BEGIN: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "noLibs" :pkgAdoptionType "b:npa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<b:npa:blee-libs:install|update>>  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun b:npa:blee-libs:install|update ()
   " #+begin_org
** DocStr: {$<pkgName} Native package adoption install or update template.
#+end_org "

 (if b:g:dev:mode?
      (straight-use-package
       '(blee-libs :local-repo "/bisos/git/bxRepos/blee/blee-libs"))
    (straight-use-package
     '(blee-libs :type git :host github :repo "bx-blee/blee-libs"))))
;;;#+END:


;; ;;;#+BEGINNOT: b:elisp:pkg:install/update :outLevel 1 :pkgsStage "noLibs" :pkgAdoptionType "bnpa" :pkgName "blee-libs"
;; (orgCmntBegin "
;; * [[elisp:(show-all)][(>]]  =defun= <<bnpa:blee-libs:install|update>> [[elisp:(org-shifttab)][<)]] E|
;; " orgCmntEnd)
;; (defun bnpa:blee-libs:install|update ()
;;  "blee-libs package adoption install|update template."
;;  (interactive)
;;  (if b:g:dev:mode?
;;      (progn
;;        (message "straight-use-package development-mode /bisos/git/bxRepos/blee/blee-libs")
;;        (straight-use-package
;;         '(blee-libs :local-repo "/bisos/git/bxRepos/blee/blee-libs"))
;;       )
;;    (progn
;;      (message "straight-use-package authorship-mode github bx-blee/blee-libs")
;;      (straight-use-package
;;       '(blee-libs :type git :host github :repo "bx-blee/blee-libs"))))
;;  )
;; ;;;#+END:

;;;#+BEGIN: b:elisp:pkg:config/main :outLevel 1 :pkgsStage "noLibs" :pkgAdoptionType "b:npa" :pkgName "blee-libs"
(orgCmntBegin "
* [[elisp:(show-all)][(>]]  =defun= <<b:npa:blee-libs:config|main>>  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
(defun b:npa:blee-libs:config|main ()
   " #+begin_org
** DocStr: *blee-libs* package adoption config template.
#+end_org "

;;;#+END:
  )

;;;#+BEGIN: b:elisp:file/provide :modName nil
(provide 'bnpa:blee-libs)
;;;#+END:

;;;#+BEGIN: b:elisp:file/endOf :outLevel 1
(orgCmntBegin "
* [[elisp:(show-all)][(>]] ~END-OF-FILE~  [[elisp:(org-shifttab)][<)]] E|
" orgCmntEnd)
;;; local variables:
;;; no-byte-compile: t
;;; end:
;;;#+END:
